"""First Migration

Revision ID: cd90f233624c
Revises: 
Create Date: 2023-03-31 15:37:08.461101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd90f233624c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URL_Shortener',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orig_url', sa.String(length=100), nullable=True),
    sa.Column('short_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('URL_Shortener')
    # ### end Alembic commands ###
